# ============================================================
# 📥 IMPORT LIBRARIES
# ============================================================
from dotenv import load_dotenv

import os
from getpass import getpass

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate


# ============================================================
# 🔐 GEMINI API KEY
# ============================================================

load_dotenv()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

if not GOOGLE_API_KEY:
    raise ValueError(
        "GOOGLE_API_KEY not found. Please check your .env file."
    )


# ============================================================
# 🤖 INITIALIZE GEMINI
# ============================================================

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=GOOGLE_API_KEY,
    temperature=0.4,
    max_retries=5,
    timeout=60
)


# ============================================================
# 🥇 CHAIN 1
# Laptop Recommendation
# ============================================================

first_prompt = ChatPromptTemplate.from_messages([
    (
        "user",
        """
You are a laptop recommendation expert.

The user has the following requirements:

{user_requirements}

Find 3 suitable laptops based on these requirements.

For each laptop provide:

- Laptop name
- Brand
- Processor
- RAM
- Storage
- GPU
- Display
- Battery
- Approximate price
- Main advantages
- Main disadvantages

Do not select a final winner.
Only provide suitable laptop options with their specifications.
"""
    )
])


# Chain 1
chain_one = first_prompt | llm


# ============================================================
# 🥈 CHAIN 2
# Analyze the laptops generated by Chain 1
# ============================================================

second_prompt = ChatPromptTemplate.from_messages([
    (
        "user",
        """
You are a laptop comparison expert.

Here are the laptop options generated by another system:

{laptop_options}

Analyze these laptops.

For each laptop discuss:

1. Performance
2. Gaming capability
3. Programming suitability
4. Machine Learning / AI suitability
5. Display
6. Battery
7. Upgradeability
8. Value for money
9. Advantages
10. Disadvantages

Then explain the major differences between the laptops.

Finally, explain which type of user each laptop is suitable for.

Do not invent specifications that are not present
in the laptop options.
"""
    )
])


# Chain 2
chain_two = second_prompt | llm


# ============================================================
# 🔄 SEQUENTIAL CHAIN
# ============================================================

def run_laptop_chain(user_requirements):

    # -----------------------------
    # Chain 1
    # -----------------------------

    response_one = chain_one.invoke({
        "user_requirements": user_requirements
    })

    laptop_options = response_one.content


    # -----------------------------
    # Chain 2
    # -----------------------------

    response_two = chain_two.invoke({
        "laptop_options": laptop_options
    })

    final_analysis = response_two.content

    return laptop_options, final_analysis


# ============================================================
# 🚀 USER INPUT
# ============================================================

user_requirements = """
Budget: ₹70,000

Purpose:
- Gaming
- Programming
- Machine Learning

Requirements:
- RAM: At least 16 GB
- Storage: At least 512 GB SSD
- Dedicated NVIDIA GPU preferred
- Good processor
- Good display
"""


# ============================================================
# ▶️ RUN
# ============================================================

laptop_options, final_analysis = run_laptop_chain(
    user_requirements
)


# ============================================================
# 📤 OUTPUT
# ============================================================

print("\n")
print("=" * 80)
print("CHAIN 1 - LAPTOP OPTIONS")
print("=" * 80)

print(laptop_options)


print("\n")
print("=" * 80)
print("CHAIN 2 - DETAILED ANALYSIS")
print("=" * 80)

print(final_analysis)